/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by `next dev`/`next build` — committed here
// only as a placeholder so the project type-checks before the first run.
